// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.domain;

import ar.edu.um.programacion2.ejemploprog2.domain.Item;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Item_Roo_Configurable {
    
    declare @type: Item: @Configurable;
    
}
