// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.model;

import ar.edu.um.programacion2.ejemploprog2.model.Combo;
import ar.edu.um.programacion2.ejemploprog2.model.ComboDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.model.ComercioDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.model.EstadoDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.model.ProductoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ComboDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ComboDataOnDemand: @Component;
    
    private Random ComboDataOnDemand.rnd = new SecureRandom();
    
    private List<Combo> ComboDataOnDemand.data;
    
    @Autowired
    ComercioDataOnDemand ComboDataOnDemand.comercioDataOnDemand;
    
    @Autowired
    EstadoDataOnDemand ComboDataOnDemand.estadoDataOnDemand;
    
    @Autowired
    ProductoDataOnDemand ComboDataOnDemand.productoDataOnDemand;
    
    public Combo ComboDataOnDemand.getNewTransientCombo(int index) {
        Combo obj = new Combo();
        setDescripcion(obj, index);
        setNombre(obj, index);
        return obj;
    }
    
    public void ComboDataOnDemand.setDescripcion(Combo obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void ComboDataOnDemand.setNombre(Combo obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public Combo ComboDataOnDemand.getSpecificCombo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Combo obj = data.get(index);
        Long id = obj.getId();
        return Combo.findCombo(id);
    }
    
    public Combo ComboDataOnDemand.getRandomCombo() {
        init();
        Combo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Combo.findCombo(id);
    }
    
    public boolean ComboDataOnDemand.modifyCombo(Combo obj) {
        return false;
    }
    
    public void ComboDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Combo.findComboEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Combo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Combo>();
        for (int i = 0; i < 10; i++) {
            Combo obj = getNewTransientCombo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
