// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.model;

import ar.edu.um.programacion2.ejemploprog2.model.Combo;
import ar.edu.um.programacion2.ejemploprog2.model.ComboDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.model.ComboIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ComboIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ComboIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ComboIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ComboIntegrationTest: @Transactional;
    
    @Autowired
    ComboDataOnDemand ComboIntegrationTest.dod;
    
    @Test
    public void ComboIntegrationTest.testCountComboes() {
        Assert.assertNotNull("Data on demand for 'Combo' failed to initialize correctly", dod.getRandomCombo());
        long count = Combo.countComboes();
        Assert.assertTrue("Counter for 'Combo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ComboIntegrationTest.testFindCombo() {
        Combo obj = dod.getRandomCombo();
        Assert.assertNotNull("Data on demand for 'Combo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Combo' failed to provide an identifier", id);
        obj = Combo.findCombo(id);
        Assert.assertNotNull("Find method for 'Combo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Combo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ComboIntegrationTest.testFindAllComboes() {
        Assert.assertNotNull("Data on demand for 'Combo' failed to initialize correctly", dod.getRandomCombo());
        long count = Combo.countComboes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Combo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Combo> result = Combo.findAllComboes();
        Assert.assertNotNull("Find all method for 'Combo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Combo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ComboIntegrationTest.testFindComboEntries() {
        Assert.assertNotNull("Data on demand for 'Combo' failed to initialize correctly", dod.getRandomCombo());
        long count = Combo.countComboes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Combo> result = Combo.findComboEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Combo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Combo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ComboIntegrationTest.testFlush() {
        Combo obj = dod.getRandomCombo();
        Assert.assertNotNull("Data on demand for 'Combo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Combo' failed to provide an identifier", id);
        obj = Combo.findCombo(id);
        Assert.assertNotNull("Find method for 'Combo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCombo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Combo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ComboIntegrationTest.testMergeUpdate() {
        Combo obj = dod.getRandomCombo();
        Assert.assertNotNull("Data on demand for 'Combo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Combo' failed to provide an identifier", id);
        obj = Combo.findCombo(id);
        boolean modified =  dod.modifyCombo(obj);
        Integer currentVersion = obj.getVersion();
        Combo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Combo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ComboIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Combo' failed to initialize correctly", dod.getRandomCombo());
        Combo obj = dod.getNewTransientCombo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Combo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Combo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Combo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ComboIntegrationTest.testRemove() {
        Combo obj = dod.getRandomCombo();
        Assert.assertNotNull("Data on demand for 'Combo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Combo' failed to provide an identifier", id);
        obj = Combo.findCombo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Combo' with identifier '" + id + "'", Combo.findCombo(id));
    }
    
}
