// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.model;

import ar.edu.um.programacion2.ejemploprog2.model.Comercio;
import ar.edu.um.programacion2.ejemploprog2.model.ComercioDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.model.ComercioIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ComercioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ComercioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ComercioIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ComercioIntegrationTest: @Transactional;
    
    @Autowired
    ComercioDataOnDemand ComercioIntegrationTest.dod;
    
    @Test
    public void ComercioIntegrationTest.testCountComercios() {
        Assert.assertNotNull("Data on demand for 'Comercio' failed to initialize correctly", dod.getRandomComercio());
        long count = Comercio.countComercios();
        Assert.assertTrue("Counter for 'Comercio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ComercioIntegrationTest.testFindComercio() {
        Comercio obj = dod.getRandomComercio();
        Assert.assertNotNull("Data on demand for 'Comercio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comercio' failed to provide an identifier", id);
        obj = Comercio.findComercio(id);
        Assert.assertNotNull("Find method for 'Comercio' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Comercio' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ComercioIntegrationTest.testFindAllComercios() {
        Assert.assertNotNull("Data on demand for 'Comercio' failed to initialize correctly", dod.getRandomComercio());
        long count = Comercio.countComercios();
        Assert.assertTrue("Too expensive to perform a find all test for 'Comercio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Comercio> result = Comercio.findAllComercios();
        Assert.assertNotNull("Find all method for 'Comercio' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Comercio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ComercioIntegrationTest.testFindComercioEntries() {
        Assert.assertNotNull("Data on demand for 'Comercio' failed to initialize correctly", dod.getRandomComercio());
        long count = Comercio.countComercios();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Comercio> result = Comercio.findComercioEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Comercio' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Comercio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ComercioIntegrationTest.testFlush() {
        Comercio obj = dod.getRandomComercio();
        Assert.assertNotNull("Data on demand for 'Comercio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comercio' failed to provide an identifier", id);
        obj = Comercio.findComercio(id);
        Assert.assertNotNull("Find method for 'Comercio' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyComercio(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Comercio' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ComercioIntegrationTest.testMergeUpdate() {
        Comercio obj = dod.getRandomComercio();
        Assert.assertNotNull("Data on demand for 'Comercio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comercio' failed to provide an identifier", id);
        obj = Comercio.findComercio(id);
        boolean modified =  dod.modifyComercio(obj);
        Integer currentVersion = obj.getVersion();
        Comercio merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Comercio' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ComercioIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Comercio' failed to initialize correctly", dod.getRandomComercio());
        Comercio obj = dod.getNewTransientComercio(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Comercio' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Comercio' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Comercio' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ComercioIntegrationTest.testRemove() {
        Comercio obj = dod.getRandomComercio();
        Assert.assertNotNull("Data on demand for 'Comercio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comercio' failed to provide an identifier", id);
        obj = Comercio.findComercio(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Comercio' with identifier '" + id + "'", Comercio.findComercio(id));
    }
    
}
