// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.model;

import ar.edu.um.programacion2.ejemploprog2.model.Producto;
import ar.edu.um.programacion2.ejemploprog2.model.ProductoDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.model.ProductoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductoIntegrationTest: @Transactional;
    
    @Autowired
    ProductoDataOnDemand ProductoIntegrationTest.dod;
    
    @Test
    public void ProductoIntegrationTest.testCountProductoes() {
        Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", dod.getRandomProducto());
        long count = Producto.countProductoes();
        Assert.assertTrue("Counter for 'Producto' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductoIntegrationTest.testFindProducto() {
        Producto obj = dod.getRandomProducto();
        Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Producto' failed to provide an identifier", id);
        obj = Producto.findProducto(id);
        Assert.assertNotNull("Find method for 'Producto' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Producto' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductoIntegrationTest.testFindAllProductoes() {
        Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", dod.getRandomProducto());
        long count = Producto.countProductoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Producto', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Producto> result = Producto.findAllProductoes();
        Assert.assertNotNull("Find all method for 'Producto' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Producto' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductoIntegrationTest.testFindProductoEntries() {
        Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", dod.getRandomProducto());
        long count = Producto.countProductoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Producto> result = Producto.findProductoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Producto' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Producto' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductoIntegrationTest.testFlush() {
        Producto obj = dod.getRandomProducto();
        Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Producto' failed to provide an identifier", id);
        obj = Producto.findProducto(id);
        Assert.assertNotNull("Find method for 'Producto' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProducto(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Producto' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductoIntegrationTest.testMergeUpdate() {
        Producto obj = dod.getRandomProducto();
        Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Producto' failed to provide an identifier", id);
        obj = Producto.findProducto(id);
        boolean modified =  dod.modifyProducto(obj);
        Integer currentVersion = obj.getVersion();
        Producto merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Producto' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", dod.getRandomProducto());
        Producto obj = dod.getNewTransientProducto(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Producto' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Producto' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Producto' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductoIntegrationTest.testRemove() {
        Producto obj = dod.getRandomProducto();
        Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Producto' failed to provide an identifier", id);
        obj = Producto.findProducto(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Producto' with identifier '" + id + "'", Producto.findProducto(id));
    }
    
}
