// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.model;

import ar.edu.um.programacion2.ejemploprog2.model.EstadoDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.model.Tags;
import ar.edu.um.programacion2.ejemploprog2.model.TagsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TagsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TagsDataOnDemand: @Component;
    
    private Random TagsDataOnDemand.rnd = new SecureRandom();
    
    private List<Tags> TagsDataOnDemand.data;
    
    @Autowired
    EstadoDataOnDemand TagsDataOnDemand.estadoDataOnDemand;
    
    public Tags TagsDataOnDemand.getNewTransientTags(int index) {
        Tags obj = new Tags();
        setNombre(obj, index);
        return obj;
    }
    
    public void TagsDataOnDemand.setNombre(Tags obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public Tags TagsDataOnDemand.getSpecificTags(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Tags obj = data.get(index);
        Long id = obj.getId();
        return Tags.findTags(id);
    }
    
    public Tags TagsDataOnDemand.getRandomTags() {
        init();
        Tags obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Tags.findTags(id);
    }
    
    public boolean TagsDataOnDemand.modifyTags(Tags obj) {
        return false;
    }
    
    public void TagsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Tags.findTagsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Tags' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Tags>();
        for (int i = 0; i < 10; i++) {
            Tags obj = getNewTransientTags(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
