// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.model;

import ar.edu.um.programacion2.ejemploprog2.model.Tags;
import ar.edu.um.programacion2.ejemploprog2.model.TagsDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.model.TagsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TagsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TagsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TagsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TagsIntegrationTest: @Transactional;
    
    @Autowired
    TagsDataOnDemand TagsIntegrationTest.dod;
    
    @Test
    public void TagsIntegrationTest.testCountTagses() {
        Assert.assertNotNull("Data on demand for 'Tags' failed to initialize correctly", dod.getRandomTags());
        long count = Tags.countTagses();
        Assert.assertTrue("Counter for 'Tags' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TagsIntegrationTest.testFindTags() {
        Tags obj = dod.getRandomTags();
        Assert.assertNotNull("Data on demand for 'Tags' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tags' failed to provide an identifier", id);
        obj = Tags.findTags(id);
        Assert.assertNotNull("Find method for 'Tags' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tags' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TagsIntegrationTest.testFindAllTagses() {
        Assert.assertNotNull("Data on demand for 'Tags' failed to initialize correctly", dod.getRandomTags());
        long count = Tags.countTagses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tags', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tags> result = Tags.findAllTagses();
        Assert.assertNotNull("Find all method for 'Tags' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tags' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TagsIntegrationTest.testFindTagsEntries() {
        Assert.assertNotNull("Data on demand for 'Tags' failed to initialize correctly", dod.getRandomTags());
        long count = Tags.countTagses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tags> result = Tags.findTagsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tags' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tags' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TagsIntegrationTest.testFlush() {
        Tags obj = dod.getRandomTags();
        Assert.assertNotNull("Data on demand for 'Tags' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tags' failed to provide an identifier", id);
        obj = Tags.findTags(id);
        Assert.assertNotNull("Find method for 'Tags' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTags(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tags' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TagsIntegrationTest.testMergeUpdate() {
        Tags obj = dod.getRandomTags();
        Assert.assertNotNull("Data on demand for 'Tags' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tags' failed to provide an identifier", id);
        obj = Tags.findTags(id);
        boolean modified =  dod.modifyTags(obj);
        Integer currentVersion = obj.getVersion();
        Tags merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tags' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TagsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Tags' failed to initialize correctly", dod.getRandomTags());
        Tags obj = dod.getNewTransientTags(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tags' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tags' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Tags' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TagsIntegrationTest.testRemove() {
        Tags obj = dod.getRandomTags();
        Assert.assertNotNull("Data on demand for 'Tags' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tags' failed to provide an identifier", id);
        obj = Tags.findTags(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Tags' with identifier '" + id + "'", Tags.findTags(id));
    }
    
}
