// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.domain;

import ar.edu.um.programacion2.ejemploprog2.domain.Cliente;
import ar.edu.um.programacion2.ejemploprog2.domain.ClienteDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ClienteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClienteDataOnDemand: @Component;
    
    private Random ClienteDataOnDemand.rnd = new SecureRandom();
    
    private List<Cliente> ClienteDataOnDemand.data;
    
    public Cliente ClienteDataOnDemand.getNewTransientCliente(int index) {
        Cliente obj = new Cliente();
        setDomicilio(obj, index);
        setEmail(obj, index);
        setNya(obj, index);
        setTelefono(obj, index);
        return obj;
    }
    
    public void ClienteDataOnDemand.setDomicilio(Cliente obj, int index) {
        String domicilio = "domicilio_" + index;
        if (domicilio.length() > 30) {
            domicilio = domicilio.substring(0, 30);
        }
        obj.setDomicilio(domicilio);
    }
    
    public void ClienteDataOnDemand.setEmail(Cliente obj, int index) {
        String email = "foo" + index + "@bar.com";
        if (email.length() > 30) {
            email = email.substring(0, 30);
        }
        obj.setEmail(email);
    }
    
    public void ClienteDataOnDemand.setNya(Cliente obj, int index) {
        String nya = "nya_" + index;
        if (nya.length() > 20) {
            nya = nya.substring(0, 20);
        }
        obj.setNya(nya);
    }
    
    public void ClienteDataOnDemand.setTelefono(Cliente obj, int index) {
        int telefono = index;
        obj.setTelefono(telefono);
    }
    
    public Cliente ClienteDataOnDemand.getSpecificCliente(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Cliente obj = data.get(index);
        Long id = obj.getId();
        return Cliente.findCliente(id);
    }
    
    public Cliente ClienteDataOnDemand.getRandomCliente() {
        init();
        Cliente obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Cliente.findCliente(id);
    }
    
    public boolean ClienteDataOnDemand.modifyCliente(Cliente obj) {
        return false;
    }
    
    public void ClienteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Cliente.findClienteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Cliente' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Cliente>();
        for (int i = 0; i < 10; i++) {
            Cliente obj = getNewTransientCliente(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
