// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.domain;

import ar.edu.um.programacion2.ejemploprog2.domain.Orden;
import ar.edu.um.programacion2.ejemploprog2.domain.OrdenDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.domain.OrdenIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OrdenIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OrdenIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OrdenIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OrdenIntegrationTest: @Transactional;
    
    @Autowired
    OrdenDataOnDemand OrdenIntegrationTest.dod;
    
    @Test
    public void OrdenIntegrationTest.testCountOrdens() {
        Assert.assertNotNull("Data on demand for 'Orden' failed to initialize correctly", dod.getRandomOrden());
        long count = Orden.countOrdens();
        Assert.assertTrue("Counter for 'Orden' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OrdenIntegrationTest.testFindOrden() {
        Orden obj = dod.getRandomOrden();
        Assert.assertNotNull("Data on demand for 'Orden' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Orden' failed to provide an identifier", id);
        obj = Orden.findOrden(id);
        Assert.assertNotNull("Find method for 'Orden' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Orden' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OrdenIntegrationTest.testFindAllOrdens() {
        Assert.assertNotNull("Data on demand for 'Orden' failed to initialize correctly", dod.getRandomOrden());
        long count = Orden.countOrdens();
        Assert.assertTrue("Too expensive to perform a find all test for 'Orden', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Orden> result = Orden.findAllOrdens();
        Assert.assertNotNull("Find all method for 'Orden' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Orden' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OrdenIntegrationTest.testFindOrdenEntries() {
        Assert.assertNotNull("Data on demand for 'Orden' failed to initialize correctly", dod.getRandomOrden());
        long count = Orden.countOrdens();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Orden> result = Orden.findOrdenEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Orden' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Orden' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OrdenIntegrationTest.testFlush() {
        Orden obj = dod.getRandomOrden();
        Assert.assertNotNull("Data on demand for 'Orden' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Orden' failed to provide an identifier", id);
        obj = Orden.findOrden(id);
        Assert.assertNotNull("Find method for 'Orden' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOrden(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Orden' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrdenIntegrationTest.testMergeUpdate() {
        Orden obj = dod.getRandomOrden();
        Assert.assertNotNull("Data on demand for 'Orden' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Orden' failed to provide an identifier", id);
        obj = Orden.findOrden(id);
        boolean modified =  dod.modifyOrden(obj);
        Integer currentVersion = obj.getVersion();
        Orden merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Orden' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrdenIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Orden' failed to initialize correctly", dod.getRandomOrden());
        Orden obj = dod.getNewTransientOrden(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Orden' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Orden' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Orden' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OrdenIntegrationTest.testRemove() {
        Orden obj = dod.getRandomOrden();
        Assert.assertNotNull("Data on demand for 'Orden' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Orden' failed to provide an identifier", id);
        obj = Orden.findOrden(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Orden' with identifier '" + id + "'", Orden.findOrden(id));
    }
    
}
