// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.domain;

import ar.edu.um.programacion2.ejemploprog2.domain.Cliente;
import ar.edu.um.programacion2.ejemploprog2.domain.ClienteDataOnDemand;
import ar.edu.um.programacion2.ejemploprog2.domain.Orden;
import ar.edu.um.programacion2.ejemploprog2.domain.OrdenDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OrdenDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrdenDataOnDemand: @Component;
    
    private Random OrdenDataOnDemand.rnd = new SecureRandom();
    
    private List<Orden> OrdenDataOnDemand.data;
    
    @Autowired
    ClienteDataOnDemand OrdenDataOnDemand.clienteDataOnDemand;
    
    public Orden OrdenDataOnDemand.getNewTransientOrden(int index) {
        Orden obj = new Orden();
        setCliente(obj, index);
        setDescripcion(obj, index);
        setFecha(obj, index);
        return obj;
    }
    
    public void OrdenDataOnDemand.setCliente(Orden obj, int index) {
        Cliente cliente = clienteDataOnDemand.getRandomCliente();
        obj.setCliente(cliente);
    }
    
    public void OrdenDataOnDemand.setDescripcion(Orden obj, int index) {
        String descripcion = "descripcion_" + index;
        if (descripcion.length() > 30) {
            descripcion = descripcion.substring(0, 30);
        }
        obj.setDescripcion(descripcion);
    }
    
    public void OrdenDataOnDemand.setFecha(Orden obj, int index) {
        Date fecha = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFecha(fecha);
    }
    
    public Orden OrdenDataOnDemand.getSpecificOrden(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Orden obj = data.get(index);
        Long id = obj.getId();
        return Orden.findOrden(id);
    }
    
    public Orden OrdenDataOnDemand.getRandomOrden() {
        init();
        Orden obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Orden.findOrden(id);
    }
    
    public boolean OrdenDataOnDemand.modifyOrden(Orden obj) {
        return false;
    }
    
    public void OrdenDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Orden.findOrdenEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Orden' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Orden>();
        for (int i = 0; i < 10; i++) {
            Orden obj = getNewTransientOrden(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
