// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.model;

<<<<<<< HEAD
import ar.edu.um.programacion2.ejemploprog2.model.Estado;
=======
>>>>>>> 2affdbd028e06842dd4cb5618442062e205bd19a
import ar.edu.um.programacion2.ejemploprog2.model.Rol;
import ar.edu.um.programacion2.ejemploprog2.model.Usuario;
import org.springframework.security.authentication.encoding.MessageDigestPasswordEncoder;

privileged aspect Usuario_Roo_JavaBean {
    
    public MessageDigestPasswordEncoder Usuario.getPasswordEncoder() {
        return this.passwordEncoder;
    }
    
    public void Usuario.setPasswordEncoder(MessageDigestPasswordEncoder passwordEncoder) {
        this.passwordEncoder = passwordEncoder;
    }
    
    public String Usuario.getUsername() {
        return this.username;
    }
    
    public void Usuario.setUsername(String username) {
        this.username = username;
    }
    
    public String Usuario.getPassword() {
        return this.password;
    }
    
    public Rol Usuario.getId_rol() {
        return this.id_rol;
    }
    
    public void Usuario.setId_rol(Rol id_rol) {
        this.id_rol = id_rol;
    }
    
<<<<<<< HEAD
    public Estado Usuario.getId_estado() {
        return this.id_estado;
    }
    
    public void Usuario.setId_estado(Estado id_estado) {
        this.id_estado = id_estado;
    }
    
=======
>>>>>>> 2affdbd028e06842dd4cb5618442062e205bd19a
}
