// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.ejemploprog2.web;

<<<<<<< HEAD
import ar.edu.um.programacion2.ejemploprog2.model.Combo;
import ar.edu.um.programacion2.ejemploprog2.model.Comercio;
import ar.edu.um.programacion2.ejemploprog2.model.Estado;
import ar.edu.um.programacion2.ejemploprog2.model.Item;
import ar.edu.um.programacion2.ejemploprog2.model.Producto;
import ar.edu.um.programacion2.ejemploprog2.model.Rol;
import ar.edu.um.programacion2.ejemploprog2.model.Tags;
=======
import ar.edu.um.programacion2.ejemploprog2.model.Rol;
>>>>>>> 2affdbd028e06842dd4cb5618442062e205bd19a
import ar.edu.um.programacion2.ejemploprog2.model.Usuario;
import ar.edu.um.programacion2.ejemploprog2.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
<<<<<<< HEAD
    public Converter<Combo, String> ApplicationConversionServiceFactoryBean.getComboToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<ar.edu.um.programacion2.ejemploprog2.model.Combo, java.lang.String>() {
            public String convert(Combo combo) {
                return new StringBuilder().append(combo.getNombre()).append(' ').append(combo.getDescripcion()).toString();
            }
        };
    }
    
    public Converter<Long, Combo> ApplicationConversionServiceFactoryBean.getIdToComboConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, ar.edu.um.programacion2.ejemploprog2.model.Combo>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Combo convert(java.lang.Long id) {
                return Combo.findCombo(id);
            }
        };
    }
    
    public Converter<String, Combo> ApplicationConversionServiceFactoryBean.getStringToComboConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, ar.edu.um.programacion2.ejemploprog2.model.Combo>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Combo convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Combo.class);
            }
        };
    }
    
    public Converter<Comercio, String> ApplicationConversionServiceFactoryBean.getComercioToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<ar.edu.um.programacion2.ejemploprog2.model.Comercio, java.lang.String>() {
            public String convert(Comercio comercio) {
                return new StringBuilder().append(comercio.getNombre()).append(' ').append(comercio.getDireccion()).append(' ').append(comercio.getTelefono()).append(' ').append(comercio.getCorreo()).toString();
            }
        };
    }
    
    public Converter<Long, Comercio> ApplicationConversionServiceFactoryBean.getIdToComercioConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, ar.edu.um.programacion2.ejemploprog2.model.Comercio>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Comercio convert(java.lang.Long id) {
                return Comercio.findComercio(id);
            }
        };
    }
    
    public Converter<String, Comercio> ApplicationConversionServiceFactoryBean.getStringToComercioConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, ar.edu.um.programacion2.ejemploprog2.model.Comercio>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Comercio convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Comercio.class);
            }
        };
    }
    
    public Converter<Estado, String> ApplicationConversionServiceFactoryBean.getEstadoToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<ar.edu.um.programacion2.ejemploprog2.model.Estado, java.lang.String>() {
            public String convert(Estado estado) {
                return new StringBuilder().append(estado.getNombre()).toString();
            }
        };
    }
    
    public Converter<Long, Estado> ApplicationConversionServiceFactoryBean.getIdToEstadoConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, ar.edu.um.programacion2.ejemploprog2.model.Estado>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Estado convert(java.lang.Long id) {
                return Estado.findEstado(id);
            }
        };
    }
    
    public Converter<String, Estado> ApplicationConversionServiceFactoryBean.getStringToEstadoConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, ar.edu.um.programacion2.ejemploprog2.model.Estado>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Estado convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Estado.class);
            }
        };
    }
    
    public Converter<Item, String> ApplicationConversionServiceFactoryBean.getItemToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<ar.edu.um.programacion2.ejemploprog2.model.Item, java.lang.String>() {
            public String convert(Item item) {
                return "(no displayable fields)";
            }
        };
    }
    
    public Converter<Long, Item> ApplicationConversionServiceFactoryBean.getIdToItemConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, ar.edu.um.programacion2.ejemploprog2.model.Item>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Item convert(java.lang.Long id) {
                return Item.findItem(id);
            }
        };
    }
    
    public Converter<String, Item> ApplicationConversionServiceFactoryBean.getStringToItemConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, ar.edu.um.programacion2.ejemploprog2.model.Item>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Item convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Item.class);
            }
        };
    }
    
    public Converter<Producto, String> ApplicationConversionServiceFactoryBean.getProductoToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<ar.edu.um.programacion2.ejemploprog2.model.Producto, java.lang.String>() {
            public String convert(Producto producto) {
                return new StringBuilder().append(producto.getNombre()).append(' ').append(producto.getPrecio()).append(' ').append(producto.getDescripcion()).toString();
            }
        };
    }
    
    public Converter<Long, Producto> ApplicationConversionServiceFactoryBean.getIdToProductoConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, ar.edu.um.programacion2.ejemploprog2.model.Producto>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Producto convert(java.lang.Long id) {
                return Producto.findProducto(id);
            }
        };
    }
    
    public Converter<String, Producto> ApplicationConversionServiceFactoryBean.getStringToProductoConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, ar.edu.um.programacion2.ejemploprog2.model.Producto>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Producto convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Producto.class);
            }
        };
    }
    
=======
>>>>>>> 2affdbd028e06842dd4cb5618442062e205bd19a
    public Converter<Rol, String> ApplicationConversionServiceFactoryBean.getRolToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<ar.edu.um.programacion2.ejemploprog2.model.Rol, java.lang.String>() {
            public String convert(Rol rol) {
                return new StringBuilder().append(rol.getNombre()).toString();
            }
        };
    }
    
    public Converter<Long, Rol> ApplicationConversionServiceFactoryBean.getIdToRolConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, ar.edu.um.programacion2.ejemploprog2.model.Rol>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Rol convert(java.lang.Long id) {
                return Rol.findRol(id);
            }
        };
    }
    
    public Converter<String, Rol> ApplicationConversionServiceFactoryBean.getStringToRolConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, ar.edu.um.programacion2.ejemploprog2.model.Rol>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Rol convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Rol.class);
            }
        };
    }
    
<<<<<<< HEAD
    public Converter<Tags, String> ApplicationConversionServiceFactoryBean.getTagsToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<ar.edu.um.programacion2.ejemploprog2.model.Tags, java.lang.String>() {
            public String convert(Tags tags) {
                return new StringBuilder().append(tags.getNombre()).toString();
            }
        };
    }
    
    public Converter<Long, Tags> ApplicationConversionServiceFactoryBean.getIdToTagsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, ar.edu.um.programacion2.ejemploprog2.model.Tags>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Tags convert(java.lang.Long id) {
                return Tags.findTags(id);
            }
        };
    }
    
    public Converter<String, Tags> ApplicationConversionServiceFactoryBean.getStringToTagsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, ar.edu.um.programacion2.ejemploprog2.model.Tags>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Tags convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Tags.class);
            }
        };
    }
    
=======
>>>>>>> 2affdbd028e06842dd4cb5618442062e205bd19a
    public Converter<Usuario, String> ApplicationConversionServiceFactoryBean.getUsuarioToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<ar.edu.um.programacion2.ejemploprog2.model.Usuario, java.lang.String>() {
            public String convert(Usuario usuario) {
                return new StringBuilder().append(usuario.getPasswordEncoder()).append(' ').append(usuario.getUsername()).append(' ').append(usuario.getPassword()).toString();
            }
        };
    }
    
    public Converter<Long, Usuario> ApplicationConversionServiceFactoryBean.getIdToUsuarioConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, ar.edu.um.programacion2.ejemploprog2.model.Usuario>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Usuario convert(java.lang.Long id) {
                return Usuario.findUsuario(id);
            }
        };
    }
    
    public Converter<String, Usuario> ApplicationConversionServiceFactoryBean.getStringToUsuarioConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, ar.edu.um.programacion2.ejemploprog2.model.Usuario>() {
            public ar.edu.um.programacion2.ejemploprog2.model.Usuario convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Usuario.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
<<<<<<< HEAD
        registry.addConverter(getComboToStringConverter());
        registry.addConverter(getIdToComboConverter());
        registry.addConverter(getStringToComboConverter());
        registry.addConverter(getComercioToStringConverter());
        registry.addConverter(getIdToComercioConverter());
        registry.addConverter(getStringToComercioConverter());
        registry.addConverter(getEstadoToStringConverter());
        registry.addConverter(getIdToEstadoConverter());
        registry.addConverter(getStringToEstadoConverter());
        registry.addConverter(getItemToStringConverter());
        registry.addConverter(getIdToItemConverter());
        registry.addConverter(getStringToItemConverter());
        registry.addConverter(getProductoToStringConverter());
        registry.addConverter(getIdToProductoConverter());
        registry.addConverter(getStringToProductoConverter());
        registry.addConverter(getRolToStringConverter());
        registry.addConverter(getIdToRolConverter());
        registry.addConverter(getStringToRolConverter());
        registry.addConverter(getTagsToStringConverter());
        registry.addConverter(getIdToTagsConverter());
        registry.addConverter(getStringToTagsConverter());
=======
        registry.addConverter(getRolToStringConverter());
        registry.addConverter(getIdToRolConverter());
        registry.addConverter(getStringToRolConverter());
>>>>>>> 2affdbd028e06842dd4cb5618442062e205bd19a
        registry.addConverter(getUsuarioToStringConverter());
        registry.addConverter(getIdToUsuarioConverter());
        registry.addConverter(getStringToUsuarioConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
